package pbo.materi;


import comboboxterhubung.entity.Fakultas;
import comboboxterhubung.entity.Jurusan;
import comboboxterhubung.service.FakultasService;
import comboboxterhubung.service.JurusanSevice;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;


/**
 *
 * @author Naufal
 */
public class guiku extends javax.swing.JFrame {

    private Connection koneksi;
    private Statement st;
    private ResultSet rs;
    public guiku() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_id = new javax.swing.JLabel();
        label_makul = new javax.swing.JLabel();
        label_sks = new javax.swing.JLabel();
        label_dosen = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_makul = new javax.swing.JTextField();
        txt_sks = new javax.swing.JTextField();
        txt_dosen = new javax.swing.JTextField();
        button_simpan = new javax.swing.JButton();
        button_update = new javax.swing.JButton();
        button_delete = new javax.swing.JButton();
        button_clear = new javax.swing.JButton();
        combofak = new javax.swing.JComboBox<>();
        combojur = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        combosem = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        keluar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(495, 440));
        setPreferredSize(new java.awt.Dimension(418, 480));
        setResizable(false);
        getContentPane().setLayout(null);

        label_id.setText("Id Mata Kuliah");
        getContentPane().add(label_id);
        label_id.setBounds(10, 60, 100, 30);

        label_makul.setText("Mata Kuliah");
        getContentPane().add(label_makul);
        label_makul.setBounds(10, 230, 100, 50);

        label_sks.setText("Jumlah SKS");
        getContentPane().add(label_sks);
        label_sks.setBounds(10, 290, 100, 30);

        label_dosen.setText("Dosen Pengajar");
        getContentPane().add(label_dosen);
        label_dosen.setBounds(10, 330, 100, 30);

        txt_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_idKeyPressed(evt);
            }
        });
        getContentPane().add(txt_id);
        txt_id.setBounds(110, 60, 273, 27);
        getContentPane().add(txt_makul);
        txt_makul.setBounds(110, 230, 273, 53);
        getContentPane().add(txt_sks);
        txt_sks.setBounds(110, 290, 40, 30);
        getContentPane().add(txt_dosen);
        txt_dosen.setBounds(110, 330, 273, 28);

        button_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Add.png"))); // NOI18N
        button_simpan.setText("Simpan");
        button_simpan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        button_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_simpanActionPerformed(evt);
            }
        });
        getContentPane().add(button_simpan);
        button_simpan.setBounds(10, 379, 80, 40);

        button_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Edit-32.png"))); // NOI18N
        button_update.setText("Update");
        button_update.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        button_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_updateActionPerformed(evt);
            }
        });
        getContentPane().add(button_update);
        button_update.setBounds(100, 379, 90, 40);

        button_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Delete-32.png"))); // NOI18N
        button_delete.setText("Delete");
        button_delete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        button_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_deleteActionPerformed(evt);
            }
        });
        getContentPane().add(button_delete);
        button_delete.setBounds(200, 380, 80, 40);

        button_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/3d bar chart.png"))); // NOI18N
        button_clear.setText("Tampil");
        button_clear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        button_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_clearActionPerformed(evt);
            }
        });
        getContentPane().add(button_clear);
        button_clear.setBounds(290, 379, 80, 40);

        combofak.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih--", "Sains dan Teknologi", "Psikologi", "Ilmu Tarbiyah dan Keguruan", "Ekonomi", "Syari'ah", "Humaniora", " " }));
        combofak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combofakActionPerformed(evt);
            }
        });
        getContentPane().add(combofak);
        combofak.setBounds(110, 110, 270, 20);

        combojur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih--" }));
        combojur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combojurActionPerformed(evt);
            }
        });
        getContentPane().add(combojur);
        combojur.setBounds(110, 150, 270, 20);

        jLabel1.setText("Fakultas");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 110, 100, 20);

        jLabel2.setText("Jurusan");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 150, 100, 20);

        combosem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih--", "Semester I", "Semester II", "Semester III", "Semester IV", "Semester V", "Semester VI", "Semester VII", "Semester VIII" }));
        getContentPane().add(combosem);
        combosem.setBounds(110, 190, 270, 20);

        jLabel3.setText("Semester");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 190, 100, 20);

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel4.setText("INPUT MATA KULIAH");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(120, 10, 310, 30);

        keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Exit.png"))); // NOI18N
        keluar.setText("Keluar");
        keluar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar);
        keluar.setBounds(380, 379, 80, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/vista_wallpapers.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 500, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_simpanActionPerformed
        String id = txt_id.getText();
        String nama = txt_makul.getText();
        String sks = txt_sks.getText();
        String dosen = txt_dosen.getText();

        try {
            Statement statement;
            statement = (Statement) konek.Koneksi().createStatement();
            statement.executeUpdate("insert into makul values ('" + id + "','"+combofak.getSelectedItem()+"','"+combojur.getSelectedItem()+"','"+combosem.getSelectedItem()+"','" + nama + "','" + sks + "','" + dosen + "');");
            statement.close();
            txt_id.setText("");
            txt_makul.setText("");
            txt_sks.setText("");
            txt_dosen.setText("");
            JOptionPane.showMessageDialog(null, "data berhasil disimpan");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "data belum masuk"+ex);
        }
    }//GEN-LAST:event_button_simpanActionPerformed

    private void button_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_deleteActionPerformed
        String id = txt_id.getText();
        try {
            Statement st = (Statement) konek.Koneksi().createStatement();
            st.executeUpdate("DELETE from makul where id_makul=('" + id + "');");
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
            txt_id.setText("");
            txt_makul.setText("");
            txt_sks.setText("");
            txt_dosen.setText("");
        } catch (Exception e) {

        }
    }//GEN-LAST:event_button_deleteActionPerformed

    private void button_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_updateActionPerformed
        String id = txt_id.getText();
        String nama = txt_makul.getText();
        String sks = txt_sks.getText();
        String dosen = txt_dosen.getText();
        try {
            Statement st;
            st = konek.Koneksi().createStatement();
            st.executeUpdate("UPDATE makul SET id_makul='"+id+"',fakultas='"+combofak.getSelectedItem()+"',jurusan='"+combojur.getSelectedItem()+"',semester='"+combosem.getSelectedItem()+"',nama_makul =  '"+nama+"', sks ="+sks+", nama_dosen =  '"+dosen+"' WHERE id_makul ="+id+";");
            JOptionPane.showMessageDialog(null, "Data Berhasil Diupdate");
            txt_id.setText("");
            txt_makul.setText("");
            txt_sks.setText("");
            txt_dosen.setText("");
    }//GEN-LAST:event_button_updateActionPerformed
     catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data gagal"+e);
        }
    }   
    private void txt_idKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_idKeyPressed
        

        
        String id=txt_id.getText();
        try{
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){    
        Statement statement = konek.Koneksi().createStatement();
        String sql = "select * from makul where id_makul="+id+"";
        
        rs = statement.executeQuery(sql);
        if(rs.next())
        {
        combofak.setSelectedItem("fakultas");
        combojur.setSelectedItem("jurusan");
        combosem.setSelectedItem("Semester");
        txt_makul.setText(rs.getString("nama_makul"));
        txt_sks.setText(rs.getString("sks"));
        txt_dosen.setText(rs.getString("nama_dosen"));
        }
        else 
        {JOptionPane.showMessageDialog(null,"Mata Kuliah Belum ada di database","Konfirmasi",JOptionPane.INFORMATION_MESSAGE);
        }
        }
        
        
       }
       catch(Exception k)
       {
           
       }
    }//GEN-LAST:event_txt_idKeyPressed

    private void button_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_clearActionPerformed
        new tampiltabel().setVisible(true);
//        try{
//            txt_id.setText("");
//            txt_makul.setText("");
//            txt_sks.setText("");
//            txt_dosen.setText("");
//        }
//        catch(Exception e){
//            
//        }
    }//GEN-LAST:event_button_clearActionPerformed

    private void combofakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combofakActionPerformed
            DefaultComboBoxModel saintek = new DefaultComboBoxModel(new String[]{"Biologi", "Matematika", "Fisikia","Kimia","Teknik Informatika","Teknik Arsitektur"});
            DefaultComboBoxModel psikologi = new DefaultComboBoxModel(new String[]{"Psikologi"});
            DefaultComboBoxModel fitk =new DefaultComboBoxModel(new String[] {"P. IPS","PGMI", "PGRA", "PAI"});
            if("Sains dan Teknologi".equals(combofak.getSelectedItem()))
            {
            combojur.setModel(saintek);
            }
            else if("Psikologi".equals(combofak.getSelectedItem()))
            {
            combojur.setModel(psikologi);
            }
            else if("Ilmu Tarbiyah dan Keguruan".equals(combofak.getSelectedItem()))
            {
            combojur.setModel(fitk);
            }
//               try{          
//               if("Sains dan Teknologi".equals(combofak.getSelectedItem())){
//               combojur.removeAllItems();
//               konek.Koneksi().createStatement();
//               String sql="select * from jurusan where id_jurusan like '1%'";
//               ResultSet rs=st.executeQuery(sql);
//               while(rs.next()){
//                   
//                   String a=rs.getString("nama_jurusan");
//                   combojur.addItem(a);
//               }
//               rs.close();
//               st.close();
//           }
//       }catch(Exception e){
//                   JOptionPane.showMessageDialog(null, e);
//                   }
    }//GEN-LAST:event_combofakActionPerformed

    private void combojurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combojurActionPerformed
         
    }//GEN-LAST:event_combojurActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        this.dispose();
    }//GEN-LAST:event_keluarActionPerformed
    
    
    
//    private abstract class ComboBoxListener implements ActionListener{
//    
//        public void actionPerformed(ActionEvent e){
//            Fakultas fakultas=(Fakultas) jComboBox1.getSelectedItem();
//            JurusanSevice jurusanservice=Main.getJurusanService();
//            List<Jurusan> jurusans=jurusanService.getJurusanByFakultas(fakultas.getIdFakultas());
//            
//            jComboBox2.removeAllItems();
//            for(Jurusan jurusan:jurusans){
//                jComboBox2.addItem(jurusan);
//            }
//        }
//    }
//    
//   
//    private void initComboBox(){
//        FakultasService fakultasService=Main.getFakultasService();  //new FakultasServiceImplHibernate();
//        List<Fakultas> fakultases=fakultasService.getAllFakultas();
//        for(Fakultas fak:fakultases){
//            jComboBox1.addItem(fak);
//        }
//        
//        jComboBox1.addActionListener(new ComboBoxListener() {});
//    }
//public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                
//
//}
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(guiku.class
//.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        
//
//} catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(guiku.class
//.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        
//
//} catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(guiku.class
//.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        
//
//} catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(guiku.class
//.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new guiku().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_clear;
    private javax.swing.JButton button_delete;
    private javax.swing.JButton button_simpan;
    private javax.swing.JButton button_update;
    private javax.swing.JComboBox<String> combofak;
    private javax.swing.JComboBox<String> combojur;
    private javax.swing.JComboBox<String> combosem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton keluar;
    private javax.swing.JLabel label_dosen;
    private javax.swing.JLabel label_id;
    private javax.swing.JLabel label_makul;
    private javax.swing.JLabel label_sks;
    private javax.swing.JTextField txt_dosen;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_makul;
    private javax.swing.JTextField txt_sks;
    // End of variables declaration//GEN-END:variables
}
