/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbd;

/**
 *
 * @author Naufal
 */
public class jual extends javax.swing.JFrame {

    /**
     * Creates new form jual
     */
    public jual() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_new = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nama_brg = new javax.swing.JTextField();
        id_trans = new javax.swing.JTextField();
        tgl_trans = new javax.swing.JTextField();
        id_brg = new javax.swing.JTextField();
        jCalendarCombo1 = new org.freixas.jcalendar.JCalendarCombo();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        harga = new javax.swing.JTextField();
        jumlah = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        tersedia = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(890, 610));
        getContentPane().setLayout(null);

        btn_new.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/New.png"))); // NOI18N
        btn_new.setText("New");
        btn_new.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newActionPerformed(evt);
            }
        });
        getContentPane().add(btn_new);
        btn_new.setBounds(10, 390, 81, 33);

        btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Add.png"))); // NOI18N
        btn_add.setText("Add =>");
        btn_add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        getContentPane().add(btn_add);
        btn_add.setBounds(100, 390, 100, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 110, 860, 270);

        jLabel1.setText("Id Transaksi");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 440, 70, 20);

        jLabel2.setText("Tanggal Transaksi");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 470, 90, 20);

        jLabel3.setText("Id Barang");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 500, 90, 20);

        jLabel4.setText("Nama Barang");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 530, 90, 20);
        getContentPane().add(nama_brg);
        nama_brg.setBounds(130, 530, 120, 20);

        id_trans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_transActionPerformed(evt);
            }
        });
        getContentPane().add(id_trans);
        id_trans.setBounds(130, 440, 120, 20);
        getContentPane().add(tgl_trans);
        tgl_trans.setBounds(130, 470, 120, 20);
        getContentPane().add(id_brg);
        id_brg.setBounds(130, 500, 120, 20);
        getContentPane().add(jCalendarCombo1);
        jCalendarCombo1.setBounds(260, 470, 170, 30);

        jLabel5.setText("Harga");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(450, 440, 60, 20);

        jLabel6.setText("Jumlah");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(450, 470, 60, 20);

        jLabel7.setText("Tersedia");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(560, 470, 50, 20);

        jLabel8.setText("Total Harga");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(450, 500, 70, 40);
        getContentPane().add(harga);
        harga.setBounds(520, 440, 120, 20);
        getContentPane().add(jumlah);
        jumlah.setBounds(520, 470, 30, 20);
        getContentPane().add(total);
        total.setBounds(520, 500, 170, 40);
        getContentPane().add(tersedia);
        tersedia.setBounds(610, 470, 30, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Shopping_Cart_Add.png"))); // NOI18N
        jLabel9.setText("PENJUALAN TOKO KOMPUTER \"ONY COMP\"");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 10, 620, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newActionPerformed
        
    }//GEN-LAST:event_btn_newActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_addActionPerformed

    private void id_transActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_transActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_transActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_new;
    private javax.swing.JTextField harga;
    private javax.swing.JTextField id_brg;
    private javax.swing.JTextField id_trans;
    private org.freixas.jcalendar.JCalendarCombo jCalendarCombo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jumlah;
    private javax.swing.JTextField nama_brg;
    private javax.swing.JTextField tersedia;
    private javax.swing.JTextField tgl_trans;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
