/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pbo;

import java.awt.Color;

/**
 *
 * @author Naufal
 */
public class gui extends javax.swing.JFrame {

    /**
     * Creates new form gui
     */
    public gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        l3 = new javax.swing.JToggleButton();
        l1 = new javax.swing.JToggleButton();
        l2 = new javax.swing.JToggleButton();
        l6 = new javax.swing.JToggleButton();
        l5 = new javax.swing.JToggleButton();
        l4 = new javax.swing.JToggleButton();
        l8 = new javax.swing.JToggleButton();
        l7 = new javax.swing.JToggleButton();
        l10 = new javax.swing.JToggleButton();
        l9 = new javax.swing.JToggleButton();
        l12 = new javax.swing.JToggleButton();
        l16 = new javax.swing.JToggleButton();
        l15 = new javax.swing.JToggleButton();
        l14 = new javax.swing.JToggleButton();
        l13 = new javax.swing.JToggleButton();
        l11 = new javax.swing.JToggleButton();
        M1 = new javax.swing.JToggleButton();
        M2 = new javax.swing.JToggleButton();
        M3 = new javax.swing.JToggleButton();
        M4 = new javax.swing.JToggleButton();
        M5 = new javax.swing.JToggleButton();
        M6 = new javax.swing.JToggleButton();
        M11 = new javax.swing.JToggleButton();
        M10 = new javax.swing.JToggleButton();
        M9 = new javax.swing.JToggleButton();
        M8 = new javax.swing.JToggleButton();
        M7 = new javax.swing.JToggleButton();
        M12 = new javax.swing.JToggleButton();
        M13 = new javax.swing.JToggleButton();
        M14 = new javax.swing.JToggleButton();
        M15 = new javax.swing.JToggleButton();
        M16 = new javax.swing.JToggleButton();
        M17 = new javax.swing.JToggleButton();
        M22 = new javax.swing.JToggleButton();
        M21 = new javax.swing.JToggleButton();
        M20 = new javax.swing.JToggleButton();
        M19 = new javax.swing.JToggleButton();
        M18 = new javax.swing.JToggleButton();
        M23 = new javax.swing.JToggleButton();
        M24 = new javax.swing.JToggleButton();
        M25 = new javax.swing.JToggleButton();
        M26 = new javax.swing.JToggleButton();
        M27 = new javax.swing.JToggleButton();
        M28 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(720, 700));
        setPreferredSize(new java.awt.Dimension(700, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(700, 600));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Amethyst", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Pilih Tempat Makan Anda");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 10, 418, 45);

        l3.setText("L3");
        l3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l3MouseClicked(evt);
            }
        });
        getContentPane().add(l3);
        l3.setBounds(280, 80, 90, 40);

        l1.setText("L1");
        l1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l1MouseClicked(evt);
            }
        });
        getContentPane().add(l1);
        l1.setBounds(60, 80, 90, 40);

        l2.setText("L2");
        l2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l2MouseClicked(evt);
            }
        });
        getContentPane().add(l2);
        l2.setBounds(170, 80, 90, 40);

        l6.setText("L6");
        l6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l6MouseClicked(evt);
            }
        });
        getContentPane().add(l6);
        l6.setBounds(610, 80, 90, 40);

        l5.setText("L5");
        l5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l5MouseClicked(evt);
            }
        });
        getContentPane().add(l5);
        l5.setBounds(500, 80, 90, 40);

        l4.setText("L4");
        l4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l4MouseClicked(evt);
            }
        });
        getContentPane().add(l4);
        l4.setBounds(390, 80, 90, 40);

        l8.setMaximumSize(new java.awt.Dimension(9, 33));
        l8.setMinimumSize(new java.awt.Dimension(9, 33));
        l8.setPreferredSize(new java.awt.Dimension(9, 33));
        l8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l8MouseClicked(evt);
            }
        });
        getContentPane().add(l8);
        l8.setBounds(660, 250, 40, 90);

        l7.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        l7.setText("L7");
        l7.setMaximumSize(new java.awt.Dimension(9, 33));
        l7.setMinimumSize(new java.awt.Dimension(9, 33));
        l7.setPreferredSize(new java.awt.Dimension(9, 33));
        l7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l7MouseClicked(evt);
            }
        });
        getContentPane().add(l7);
        l7.setBounds(660, 140, 40, 90);

        l10.setMaximumSize(new java.awt.Dimension(9, 33));
        l10.setMinimumSize(new java.awt.Dimension(9, 33));
        l10.setPreferredSize(new java.awt.Dimension(9, 33));
        getContentPane().add(l10);
        l10.setBounds(660, 470, 40, 90);

        l9.setMaximumSize(new java.awt.Dimension(9, 33));
        l9.setMinimumSize(new java.awt.Dimension(9, 33));
        l9.setPreferredSize(new java.awt.Dimension(9, 33));
        l9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l9MouseClicked(evt);
            }
        });
        getContentPane().add(l9);
        l9.setBounds(660, 360, 40, 90);

        l12.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(l12);
        l12.setBounds(500, 580, 90, 40);
        getContentPane().add(l16);
        l16.setBounds(60, 580, 90, 40);
        getContentPane().add(l15);
        l15.setBounds(170, 580, 90, 40);
        getContentPane().add(l14);
        l14.setBounds(280, 580, 90, 40);
        getContentPane().add(l13);
        l13.setBounds(390, 580, 90, 40);
        getContentPane().add(l11);
        l11.setBounds(610, 580, 90, 40);

        M1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        M1.setText("M1");
        M1.setMinimumSize(new java.awt.Dimension(33, 33));
        getContentPane().add(M1);
        M1.setBounds(210, 170, 40, 40);

        M2.setMinimumSize(new java.awt.Dimension(33, 33));
        getContentPane().add(M2);
        M2.setBounds(280, 170, 40, 40);

        M3.setMinimumSize(new java.awt.Dimension(33, 33));
        getContentPane().add(M3);
        M3.setBounds(350, 170, 40, 40);

        M4.setMinimumSize(new java.awt.Dimension(33, 33));
        getContentPane().add(M4);
        M4.setBounds(420, 170, 40, 40);

        M5.setMinimumSize(new java.awt.Dimension(33, 33));
        getContentPane().add(M5);
        M5.setBounds(490, 170, 40, 40);

        M6.setMinimumSize(new java.awt.Dimension(33, 33));
        M6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M6ActionPerformed(evt);
            }
        });
        getContentPane().add(M6);
        M6.setBounds(560, 170, 40, 40);

        M11.setMinimumSize(new java.awt.Dimension(33, 33));
        getContentPane().add(M11);
        M11.setBounds(530, 250, 40, 40);

        M10.setMinimumSize(new java.awt.Dimension(33, 33));
        getContentPane().add(M10);
        M10.setBounds(460, 250, 40, 40);

        M9.setMinimumSize(new java.awt.Dimension(33, 33));
        getContentPane().add(M9);
        M9.setBounds(380, 250, 40, 40);

        M8.setMinimumSize(new java.awt.Dimension(33, 33));
        getContentPane().add(M8);
        M8.setBounds(310, 250, 40, 40);

        M7.setMinimumSize(new java.awt.Dimension(33, 33));
        getContentPane().add(M7);
        M7.setBounds(240, 250, 40, 40);

        M12.setMinimumSize(new java.awt.Dimension(33, 33));
        getContentPane().add(M12);
        M12.setBounds(210, 330, 40, 40);

        M13.setMinimumSize(new java.awt.Dimension(33, 33));
        getContentPane().add(M13);
        M13.setBounds(280, 330, 40, 40);

        M14.setMinimumSize(new java.awt.Dimension(33, 33));
        getContentPane().add(M14);
        M14.setBounds(350, 330, 40, 40);

        M15.setMinimumSize(new java.awt.Dimension(33, 33));
        getContentPane().add(M15);
        M15.setBounds(420, 330, 40, 40);

        M16.setMinimumSize(new java.awt.Dimension(33, 33));
        getContentPane().add(M16);
        M16.setBounds(490, 330, 40, 40);

        M17.setMinimumSize(new java.awt.Dimension(33, 33));
        M17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M17ActionPerformed(evt);
            }
        });
        getContentPane().add(M17);
        M17.setBounds(560, 330, 40, 40);

        M22.setMinimumSize(new java.awt.Dimension(33, 33));
        getContentPane().add(M22);
        M22.setBounds(530, 410, 40, 40);

        M21.setMinimumSize(new java.awt.Dimension(33, 33));
        getContentPane().add(M21);
        M21.setBounds(460, 410, 40, 40);

        M20.setMinimumSize(new java.awt.Dimension(33, 33));
        getContentPane().add(M20);
        M20.setBounds(380, 410, 40, 40);

        M19.setMinimumSize(new java.awt.Dimension(33, 33));
        getContentPane().add(M19);
        M19.setBounds(310, 410, 40, 40);

        M18.setMinimumSize(new java.awt.Dimension(33, 33));
        getContentPane().add(M18);
        M18.setBounds(240, 410, 40, 40);

        M23.setMinimumSize(new java.awt.Dimension(33, 33));
        getContentPane().add(M23);
        M23.setBounds(210, 490, 40, 40);

        M24.setMinimumSize(new java.awt.Dimension(33, 33));
        getContentPane().add(M24);
        M24.setBounds(280, 490, 40, 40);

        M25.setMinimumSize(new java.awt.Dimension(33, 33));
        getContentPane().add(M25);
        M25.setBounds(350, 490, 40, 40);

        M26.setMinimumSize(new java.awt.Dimension(33, 33));
        getContentPane().add(M26);
        M26.setBounds(420, 490, 40, 40);

        M27.setMinimumSize(new java.awt.Dimension(33, 33));
        getContentPane().add(M27);
        M27.setBounds(490, 490, 40, 40);

        M28.setMinimumSize(new java.awt.Dimension(33, 33));
        M28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M28ActionPerformed(evt);
            }
        });
        getContentPane().add(M28);
        M28.setBounds(560, 490, 40, 40);

        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 260, 0, 0);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void M6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_M6ActionPerformed

    private void M17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_M17ActionPerformed

    private void M28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_M28ActionPerformed

    private void l1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l1MouseClicked
        if(l1.isSelected()==true){
            l1.setBackground(Color.BLUE);
        }
        else{
            l1.setBackground(Color.GRAY);
        }
    }//GEN-LAST:event_l1MouseClicked

    private void l2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l2MouseClicked
        if(l2.isSelected()==true){
            l2.setBackground(Color.BLUE);
        }
        else{
            l2.setBackground(Color.GRAY);
        }
    }//GEN-LAST:event_l2MouseClicked

    private void l3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l3MouseClicked
        // TODO add your handling code here:
        if(l3.isSelected()==true){
            l3.setBackground(Color.BLUE);
        }
        else{
            l3.setBackground(Color.GRAY);
        }
    }//GEN-LAST:event_l3MouseClicked

    private void l4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l4MouseClicked
        // TODO add your handling code here:
        if(l4.isSelected()==true){
            l4.setBackground(Color.BLUE);
        }
        else{
            l4.setBackground(Color.GRAY);
        }
    }//GEN-LAST:event_l4MouseClicked

    private void l5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l5MouseClicked
        // TODO add your handling code here:
        if(l5.isSelected()==true){
            l5.setBackground(Color.BLUE);
        }
        else{
            l5.setBackground(Color.GRAY);
        }
    }//GEN-LAST:event_l5MouseClicked

    private void l6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l6MouseClicked
        // TODO add your handling code here:
        if(l6.isSelected()==true){
            l6.setBackground(Color.BLUE);
        }
        else{
            l6.setBackground(Color.GRAY);
        }
    }//GEN-LAST:event_l6MouseClicked

    private void l7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l7MouseClicked
        // TODO add your handling code here:
        if(l7.isSelected()==true){
            l7.setBackground(Color.BLUE);
        }
        else{
            l7.setBackground(Color.GRAY);
        }
    }//GEN-LAST:event_l7MouseClicked

    private void l8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l8MouseClicked
        // TODO add your handling code here:
        if(l8.isSelected()==true){
            l8.setBackground(Color.BLUE);
        }
        else{
            l8.setBackground(Color.GRAY);
        }
    }//GEN-LAST:event_l8MouseClicked

    private void l9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l9MouseClicked
        // TODO add your handling code here:
        if(l9.isSelected()==true){
            l9.setBackground(Color.BLUE);
        }
        else{
            l9.setBackground(Color.GRAY);
        }
    }//GEN-LAST:event_l9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton M1;
    private javax.swing.JToggleButton M10;
    private javax.swing.JToggleButton M11;
    private javax.swing.JToggleButton M12;
    private javax.swing.JToggleButton M13;
    private javax.swing.JToggleButton M14;
    private javax.swing.JToggleButton M15;
    private javax.swing.JToggleButton M16;
    private javax.swing.JToggleButton M17;
    private javax.swing.JToggleButton M18;
    private javax.swing.JToggleButton M19;
    private javax.swing.JToggleButton M2;
    private javax.swing.JToggleButton M20;
    private javax.swing.JToggleButton M21;
    private javax.swing.JToggleButton M22;
    private javax.swing.JToggleButton M23;
    private javax.swing.JToggleButton M24;
    private javax.swing.JToggleButton M25;
    private javax.swing.JToggleButton M26;
    private javax.swing.JToggleButton M27;
    private javax.swing.JToggleButton M28;
    private javax.swing.JToggleButton M3;
    private javax.swing.JToggleButton M4;
    private javax.swing.JToggleButton M5;
    private javax.swing.JToggleButton M6;
    private javax.swing.JToggleButton M7;
    private javax.swing.JToggleButton M8;
    private javax.swing.JToggleButton M9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToggleButton l1;
    private javax.swing.JToggleButton l10;
    private javax.swing.JToggleButton l11;
    private javax.swing.JToggleButton l12;
    private javax.swing.JToggleButton l13;
    private javax.swing.JToggleButton l14;
    private javax.swing.JToggleButton l15;
    private javax.swing.JToggleButton l16;
    private javax.swing.JToggleButton l2;
    private javax.swing.JToggleButton l3;
    private javax.swing.JToggleButton l4;
    private javax.swing.JToggleButton l5;
    private javax.swing.JToggleButton l6;
    private javax.swing.JToggleButton l7;
    private javax.swing.JToggleButton l8;
    private javax.swing.JToggleButton l9;
    // End of variables declaration//GEN-END:variables
}
